modLoader = "javafml"
loaderVersion = "[31,)"
issueTrackerURL = "${mod_issues_url}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "${mod_url}"
#logoFile = "logo.png"
authors = "Sangar"
description = '''
Modern computers for the modern player.
'''

[[dependencies.scannable]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version_min},)"
ordering = "NONE"
side = "BOTH"
[[dependencies.scannable]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version_min}]"
ordering = "NONE"
side = "BOTH"
